fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
lincc.core:
    resource: "@LinCCCoreBundle/Controller/"
    type:     annotation
    prefix:   /
lincc.tables:
    resource: "@LinCCTablesBundle/Controller/"
    type:     annotation
    prefix:   /
